### ISSUE TITLE
Identify Half-Way Checkpoint stories

### ISSUE THREAD

**Issue by Tommy-Sand** [CMPUT301F22T02/well-fed#30]

**Comment by madisonbradley112** [comment]
I created a "half-way checkpoint" label for issues to assign to the user stories.

Let's consider the 4 categories: Meal Plan, Ingredients, Recipes, and Shopping Cart. I think we should aim to complete one "section" first, so we have something "done-done" to show at each point.

First, I think basic Ingredients related user stories should be completed earliest. This is because many other user stories rely on these classes being completed. I think the Ingredients section, at the least, should be done by the halfway checkpoint.

Next, I think Recipes should be completed, as Meal Plan relies heavily on both Ingredients and Recipes. Also, Shopping Cart relies heavily on Ingredients and Meal Plan. These should be our first priority, as they are simplest (but still a very important starting point)! The complexity of Meal Plan and Shopping Card can be saved for our Final Checkpoint, once we refine the design of Ingredients and Recipes.

Thus, I propose the following user stories for the half way checkpoint: Note that these are more than half, so the risk level for this group is high. 

US 01.01.01
US 01.02.01
US 01.03.01
US 01.04.01
US 01.05.01
US 01.06.01
US 02.01.01
US 02.02.01
US 02.03.01
US 02.04.01
US 02.05.01
US 02.06.01
US 02.07.01
US 02.08.01

Let me know what you think!

**Comment by madisonbradley112** [comment]
Added labels to the mentioned user stories.
