### ISSUE TITLE
Address Feedback: Project Part 2 - Product Backlog

### ISSUE THREAD

**Issue by steventango** [CMPUT301F22T02/well-fed#90]
# Feedback
## Score
3/3

## Comment
* Numbered, tracked, and organized requirements
* Comprehensive requirements
* Complete story point estimates
* Complete risk levels
* Displays understanding of requirements specification/elicitation
* Requirements noted for half-way checkpoint

**Comment by madisonbradley112** [comment]
Thank you for the feedback on our product backlog - much appreciated. 

Since no changes were requested, we will leave the product backlog structure as it is. 

Any requirements completed by the half-way checkpoint will have the issue label updated for ["half way checkpoint".](https://github.com/CMPUT301F22T02/well-fed/issues?q=is%3Aopen+is%3Aissue+label%3A%22half+way+checkpoint%22)
